export {
  BEAT_AVOID_RADIUS_PX,
  BEAT_SELECT_RADIUS_PX,
  DEFAULT_VISUALIZATION_INDEX,
  EDGE_SELECT_RADIUS_PX,
  MAX_EDGE_SAMPLES,
  MAX_EDGES_BASE,
  VISUALIZATION_LABELS,
} from "@forever-jukebox/engine/constants/visualization";

export const ANALYSIS_POLL_INTERVAL_MS = 3000;
export const LISTEN_TIMER_INTERVAL_MS = 200;
export const TOP_SONGS_LIMIT = 25;
